### ISSUE TITLE
[FEATURE] 웹 표준 검사 및 CSS 개선

### ISSUE THREAD

**Issue by nayeongdev** [HotCake-Tanghuru/HotCake-FE#3]
**Feature 요청에 대한 설명**
프론트엔드 코드의 리팩토링을 진행하여 유지보수성과 코드의 가독성, 효율성을 개선해야 합니다. 

**해결하고자 하는 문제(Why)**
1. 웹 표준 검사 및 마크업 수정
현재 코드는 웹 표준을 준수하지 않는 요소들이 포함되어 있습니다. 이로 인해 웹 페이지의 호환성이 저하되고, 검색 엔진 최적화에도 영향을 줄 수 있습니다. 
2. 중복된 CSS 수정
현재 코드는 여러 곳에서 중복되는 CSS가 사용되고 있습니다. 이로 인해 코드의 가독성이 저하되고 유지보수가 어려워집니다. 

**원하는 솔루션 설명(How)**
1. The W3C Markup Validation Service를 이용하여 웹 표준을 검사하고, 검사 결과를 바탕으로 마크업을 수정해야 합니다.
2.  중복된 CSS를 확인하고, 공통으로 사용되는 CSS를 추출하여 수정해야 합니다.

**TO-DO**
- [x] The W3C Markup Validation Service를 이용하여 웹 표준 검사 진행
- [x] 웹 표준 검사 결과에 따라 마크업 수정
- [x] 중복되는 CSS를 확인하고 공통 CSS를 추출
- [x] 공통 CSS를 수정하여 코드에 적용

**기타**
웹 표준 검사 : [The W3C Markup Validation Service](https://validator.w3.org/#validate_by_input)

**Comment by jungloopy** [comment]
감사합니다 !!!!!!!!!!!!
